lista = ["manzana","uva",'platano','arándano']

lista.append('papaya')
lista.append('mango')
print (lista)
lista2 = lista.copy()
lista.clear()
print (lista)
lista.append('frutilla')
lista2.append('platano')
print(lista)
print (lista2) 
lista3 = lista2.count('platano')
print(lista3)

lista.extend(lista2)
print(lista)
lista4 = lista.index('platano',4)
print(lista4)
lista.insert(1,'mora')
print(lista)
lista5 = lista.pop(3)
print(lista5)
lista.remove('papaya')
print(lista)
lista.reverse()
print(lista)
lista.sort()
print(lista)